### ISSUE TITLE
cannot import name copy_bezier_curve

### ISSUE THREAD

**Issue by ban3bbal000** [luckylyk/curvedeformereditor#4]
Hi,

I'm really interested to try out this tool but sadly when I'm trying to load the script I got this error: "cannot import name copy_bezier_curve". If you have a solution for it I would be happy to hear it. Thank you.

Balázs

**Comment by luckylyk** [comment]
damn, i thaugh i fixed that one. I probably just did on the production deployed version.
Let me take a look.

**Comment by luckylyk** [comment]
ok this was fixed a while ago but i forgot to publish the change :)
it is done now
